default_install_hook_types: [pre-commit, commit-msg]
default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        name: "ruff lint"
        files: "^backend/"
      - id: ruff-format
        name: "ruff format"
        files: "^backend/"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.2.0"
    hooks:
      - id: mypy
        # https://github.com/pre-commit/pre-commit/issues/2041
        additional_dependencies:
          [types-requests, types-PyYAML==5.4.12, types-toml]
